### ISSUE TITLE
Pywonders

### ISSUE THREAD

**Issue by neeoder** [ScienceGamez/pygame_cards#1]
When I try to run one of the example scripts, it gives me the error: "ModuleNotFoundError: No module named 'pywonders'". I tried to install that package, but pip couldn't find it, so I searched on google, but found nothing about this package either!

**Comment by lionel42** [comment]
Thanks for reporting,
I fixed that on github in commit 0cdd6d12a17fbb7bc9c899d8111c484d0329a5f0 
I will update the pypi repository with it and let you know once done

**Comment by neeoder** [comment]
Thank you for repliyng, I'm excited!

**Comment by lionel42** [comment]
@neeoder  I just uploaded the new version on pypi:

Please try and let me know if you manage to do something.
As you can guess the package is still in early developement so there might be few bugs, but I am happy to help ;) 

```
pip install --upgrade pygame-cards
```

**Comment by neeoder** [comment]
Everything works now! Thanks for your quick answer
